import 'package:flutter/material.dart';

final amenitiesIconMap = {
  'Adjoining Rooms': Icons.living_outlined,
  'Iron & Ironing Board': Icons.iron_outlined,
  'Bed Linen & Towels': Icons.bed_outlined,
  'Washing Machine': Icons.local_laundry_service_outlined,
  'Dishwasher': Icons.local_laundry_service_outlined,
  'Cable TV': Icons.cable_outlined,
  'Terrace': Icons.balcony_outlined,
  'satellite TV': Icons.satellite_alt_outlined,
  'internet connection': Icons.wifi,
  'air conditioning': Icons.ac_unit_outlined,
  'garden': Icons.grass,
  'Private parking': Icons.local_parking,
  'No Pets Allowed': Icons.not_interested_rounded,
  'Heating': Icons.heat_pump,
  'Pets accepted under request': Icons.pets,
  'No parties': Icons.pan_tool_rounded,
  'essentials (towels, pillows, bed linen, soap, toilet paper)': Icons.battery_charging_full,
  'No Smoking Rooms/Facilities': Icons.smoke_free,
  'Outdoor Parking': Icons.local_parking,
  'window guards': Icons.grid_4x4,
  'Wheelchair access possible': Icons.accessible_outlined,
  'Underground parking': Icons.local_parking,
  'Elevator': Icons.elevator_outlined,
  'Smoke Detectors': Icons.smoke_free,
  'Luxury': Icons.diamond,
  'Carbon Monoxide Detector': Icons.sensors_rounded,
  'designated smoking area': Icons.smoking_rooms,
  'Private pool': Icons.pool_outlined,
  'Guarded parking': Icons.local_parking,
  'swimming pool': Icons.pool_outlined,
  'Free cot on request': Icons.card_giftcard,
  'Garden (Private)': Icons.grass_outlined,
  'private entrance': Icons.door_sliding_outlined,
  'Crockery & Cutlery': Icons.flatware_outlined,
  'Toiletries': Icons.wash_outlined,
  'Kitchen': Icons.kitchen,
  'oven': Icons.microwave_outlined,
  'microwave': Icons.microwave_outlined,
  'fridge': Icons.kitchen_outlined,
  'coffee maker': Icons.coffee_maker,
  'heating': Icons.heat_pump_outlined,
  'Laundry': Icons.water_sharp,
  'Breakfast': Icons.free_breakfast_outlined,
  'stove': Icons.microwave_outlined,
  'Luggage Storage Facilities': Icons.luggage_outlined,
  'hanger': Icons.dry_cleaning_outlined,
  'Bed Linen': Icons.bed_outlined,
  'Iron': Icons.iron_outlined,
  'Pets are welcome': Icons.pets,
  'Cribs Available': Icons.bedroom_baby_outlined,
  'Free Parking': Icons.local_parking,
  'Wireless Internet': Icons.wifi,
  'Refrigerator': Icons.kitchen_outlined,
  'Free parking on the street': Icons.local_parking,
  'Laptop workspace': Icons.laptop,
  'hot water': Icons.water,
  'beachfront': Icons.beach_access_outlined,
  'single level home': Icons.home_outlined,
  'cooking basics': Icons.blender_outlined,
  'extra pillows and blankets': Icons.library_add_outlined,
  'Smoking not allowed': Icons.smoke_free,
  'Suitable for infants': Icons.child_care_outlined,
  'On street parking': Icons.local_parking,
  'a door to the terrace': Icons.door_front_door_outlined,
  'spa pool': Icons.pool_outlined,
};
