import '../../models/property.dart';

List<Property> propertiesDummyData = [
  Property(
    id: 1,
    title: "Cozy Beachfront Bungalow",
    type: "bungalow",
    location: "Hammamet",
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1.5,
    petsAllowed: false,
    amenities: ["Wifi", "Air conditioning", "Ocean view", "Private patio"],
    description: "Wake up to the sound of waves in this charming bungalow steps from the beach. Perfect for a relaxing getaway with family or friends.",
    pricePerNight: 250,
    imagePath: 'assets/images/house1.jpeg',
    rating: 3.8,
    reviews: 112,
  ),
  Property(
    id: 2,
    title: "Modern City Loft with Balcony",
    type: "apartment",
    location: "Marsa",
    guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    petsAllowed: true,
    amenities: ["Wifi", "Elevator", "Gym", "Balcony access"],
    description: "Enjoy stunning city views from your private balcony in this chic loft. Centrally located for easy access to all Chicago has to offer.",
    pricePerNight: 180,
    imagePath: 'assets/images/house2.jpeg',
    rating: 4.8,
    reviews: 53,
  ),
  Property(
    id: 3,
    title: "Spacious Cabin in the Woods",
    type: "cabin",
    location: "Ain Drahem",
    guests: 6,
    bedrooms: 3,
    beds: 5,
    bathrooms: 2,
    petsAllowed: false,
    amenities: ["Wifi", "Fireplace", "Hot tub", "Hiking trails nearby"],
    description: "Reconnect with nature in this cozy cabin nestled amongst the pines. Ideal for a family retreat or adventure weekend with friends.",
    pricePerNight: 300,
    imagePath: 'assets/images/house3.jpeg',
    rating: 4.2,
    reviews: 46,
  ),
  Property(
    id: 4,
    title: "Luxury Treehouse with Mountain Views",
    type: "treehouse",
    location: "Bizert",
    guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    petsAllowed: false,
    amenities: ["Wifi", "Jacuzzi tub", "Deck with fireplace", "Unique stay"],
    description: "Experience the magic of staying in a treehouse surrounded by breathtaking mountain scenery. Unwind in the jacuzzi tub and enjoy the fresh mountain air.",
    pricePerNight: 450,
    imagePath: 'assets/images/house4.jpeg',
    rating: 4.1,
    reviews: 87,
  ),
  Property(
    id: 5,
    title: "Charming Vineyard Cottage",
    type: "cottage",
    location: "Paris",
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 1,
    petsAllowed: false,
    amenities: ["Wifi", "Wine tasting tours", "Private garden", "Outdoor dining area"],
    description:
        "Immerse yourself in the Napa Valley lifestyle at this charming cottage. Sip wine on the patio, explore nearby vineyards, and enjoy the serenity of the countryside.",
    pricePerNight: 280,
    imagePath: 'assets/images/house5.jpeg',
    rating: 3.8,
    reviews: 96,
  ),
  Property(
    id: 6,
    title: "Quirky Airstream Trailer in Desert",
    type: "trailer",
    location: "Hammamet",
    petsAllowed: true,
    amenities: ["Wifi", "Stunning desert views", "Stargazing opportunities", "Outdoor camping experience"],
    description:
        "Embark on an unforgettable desert adventure in this vintage Airstream trailer. Camp under the stars, gaze at the milky way, and soak in the tranquility of the desert.",
    pricePerNight: 150,
    rating: 3.3,
    reviews: 67,
  ),
  Property(
    id: 7,
    title: "Modern Ski Condo with Hot Tub",
    type: "condo",
    location: "Marsa",
    guests: 6,
    bedrooms: 3,
    beds: 6,
    bathrooms: 2,
    petsAllowed: false,
    amenities: ["Wifi", "Ski-in/ski-out access"],
    pricePerNight: 320,
    rating: 2.9,
    reviews: 18,
  ),
];
